"""empty message

Revision ID: bc44d8b8c41e
Revises:
Create Date: 2021-06-28 12:46:56.638807

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bc44d8b8c41e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("first_name", sa.String(length=40), nullable=False),
        sa.Column("last_name", sa.String(length=40), nullable=False),
        sa.Column("username", sa.String(length=40), nullable=False),
        sa.Column("is_bot", sa.Boolean(), nullable=True),
        sa.Column("is_super_user", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_chat_id"), "user", ["chat_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_chat_id"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
