version: '3'

services:

  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    networks:
      - bot-network
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:7543:5432
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  test_db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - ${TEST_DB_HOST}:${TEST_DB_PORT}:5432
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}


  run_bot:
    build:
      context: .
      dockerfile:
        Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bot-network
    command:
      sh run_bot.sh


networks:
  bot-network:
    external: false

volumes:
  db_volume:
    external: false
